general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "Buttonless"
padding = { x = 5, y = 5 }

[terminal]
shell = { program = "/opt/homebrew/bin/fish", args = [ "-c", "zellij" ] }

[font]
normal = { family = "SpaceMono Nerd Font", style = "Regular" }
size = 12.5
