theme = "tokyonight-night"
line-height = 1.2

[cursor]
shape = 'block'
blinking = true
blinking-interval = 800

[editor]
program = "nvim"
args = []

[fonts]
size = 13
features = []
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = false

[fonts.regular]
family = "VulfMonoCode Nerd Font Mono"
style = "Regular"

[fonts.italic]
family = "VulfMonoCode Nerd Font Mono"
style = "Italic"

[shell]
program = "/usr/bin/fish"

[platform]
macos.shell.program = "/opt/homebrew/bin/fish"
macos.renderer.backend = "Metal"
macos.window.decorations = "Transparent"
