theme = "tokyonight-night"

[cursor]
shape = 'block'
blinking = true
blinking-interval = 800

[editor]
program = "nvim"
args = []

[fonts]
size = 13
features = []
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = true
additional-dirs = []

[fonts.regular]
family = "SpaceMono Nerd Font"
style = "default"

[fonts.italic]
family = "Maple Mono NF"
style = "default"

[shell]
program = "/usr/bin/fish"

[platform]
macos.shell.program = "/opt/homebrew/bin/fish"
macos.renderer.backend = "Metal"
macos.window.decorations = "Transparent"
