#!/usr/bin/env bash

# ██░ ██▓█████ ██▀███  ▄▄▄▄    ██████▄▄▄█████▓██▓    █    ██  █████▄▄▄█████▓
# ▓██░ ██▓█   ▀▓██ ▒ ██▓█████▄▒██    ▒▓  ██▒ ▓▓██▒    ██  ▓██▓██   ▒▓  ██▒ ▓▒
# ▒██▀▀██▒███  ▓██ ░▄█ ▒██▒ ▄█░ ▓██▄  ▒ ▓██░ ▒▒██░   ▓██  ▒██▒████ ░▒ ▓██░ ▒░
# ░▓█ ░██▒▓█  ▄▒██▀▀█▄ ▒██░█▀   ▒   ██░ ▓██▓ ░▒██░   ▓▓█  ░██░▓█▒  ░░ ▓██▓ ░
# ░▓█▒░██░▒████░██▓ ▒██░▓█  ▀█▒██████▒▒ ▒██▒ ░░██████▒▒█████▓░▒█░     ▒██▒ ░
# ▒ ░░▒░░░ ▒░ ░ ▒▓ ░▒▓░▒▓███▀▒ ▒▓▒ ▒ ░ ▒ ░░  ░ ▒░▓  ░▒▓▒ ▒ ▒ ▒ ░     ▒ ░░
# ▒ ░▒░ ░░ ░  ░ ░▒ ░ ▒▒░▒   ░░ ░▒  ░ ░   ░   ░ ░ ▒  ░░▒░ ░ ░ ░         ░
# ░  ░░ ░  ░    ░░   ░ ░    ░░  ░  ░   ░       ░ ░   ░░░ ░ ░ ░ ░     ░
# ░  ░  ░  ░  ░  ░     ░           ░             ░  ░  ░

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xrandr --dpi 168 &

# Set a random wallpaper as backround on each startup
~/.config/herbstluftwm/wallpaper.sh

# Remove the existing keybinds
hc keyunbind --all

# Keybinds
# Win key as MOD
Mod=Mod4
hc keybind $Mod-d spawn dmenu_run
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-l spawn slock
hc keybind $Mod-Return spawn urxvt #${TERMINAL:-xterm} # use your $TERMINAL with xterm as fallback
#hc keybind $Mod-d spawn rofi -show run
hc keybind $Mod-c spawn firefox
hc keybind $Mod-v spawn /opt/forticlient-sslvpn/forticlientsslvpn.sh
#XF86Keys
hc keybind XF86Search spawn rofi -show run

# PULSE
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +2%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -2%
hc keybind XF86AudioMute spawn pactl set-sink-mute 0 toggle
# ALSA
#hc keybind XF86AudioRaiseVolume spawn amixer set Master 5%+
#hc keybind XF86AudioLowerVolume spawn amixer set Master 5%-
#hc keybind XF86AudioMute spawn amixer set Master 1+ toggle

# New wallpaper
hc keybind $Mod-w spawn ~/.config/herbstluftwm/wallpaper.sh

# Screen brightness
hc keybind XF86MonBrightnessUp spawn ~/.config/herbstluftwm/xrandr.sh +
hc keybind XF86MonBrightnessDown spawn ~/.config/herbstluftwm/xrandr.sh -

hc keybind XF86Tools spawn nmcli_dmenu
hc keybind XF86Explorer spawn slock
hc keybind XF86LaunchA spawn echo "nothing yet"
hc keybind XF86Display spawn xrandr --output LVDS1 --rate 60 --mode 2560x1440 --fb 2560x1440 --panning 2560x1440* --output HDMI1 --mode 2560x1440 --same-as LVDS1
hc keybind XF86AudioMicMute spawn echo "nothing yet"

# Frame and Windows interaction
# Focusing
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right
# Moving
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right
# Splitting
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Control-space split explode
# Resizing
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# Tags
tag_names=(0001 0010 0011 0100 0101 0110 0111 1000 1001)
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# Blue color theme
#hc attr theme.tiling.reset 1
#hc attr theme.floating.reset 1
#hc set frame_border_active_color '#222222'
#hc set frame_border_normal_color '#101010'
#hc set frame_bg_normal_color '#565656'
#hc set frame_bg_active_color '#15598F'
#hc set frame_border_width 1
#hc set always_show_frame 1
#hc set frame_bg_transparent 1
#hc set frame_transparent_width 5
#hc set frame_gap 4
#hc attr theme.active.color '#009DD8'
#hc attr theme.normal.color '#454545'
#hc attr theme.urgent.color orange
#hc attr theme.inner_width 1
#hc attr theme.inner_color black
#hc attr theme.border_width 3
#hc attr theme.floating.border_width 4
#hc attr theme.floating.outer_width 1
#hc attr theme.floating.outer_color black
#hc attr theme.active.inner_color '#3E4A00'
#hc attr theme.active.outer_color '#3E4A00'
#hc attr theme.background_color '#141414'
#hc set window_gap 0
#hc set frame_padding 0
#hc set smart_window_surroundings 0
#hc set smart_frame_surroundings 1
#hc set mouse_recenter_gap 0

# lb.theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#AA1'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#1AA'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

~/.config/herbstluftwm/panel.sh
